cmake_minimum_required(VERSION 3.16)

include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/SysrootManifest.cmake")

set(import_script "${CMAKE_CURRENT_LIST_DIR}/../../cmake/ImportSysroot.cmake")
string(RANDOM LENGTH 12 fixture_id)
if(DEFINED ENV{TMPDIR} AND NOT "$ENV{TMPDIR}" STREQUAL "")
    set(temp_root "$ENV{TMPDIR}")
elseif(DEFINED ENV{TEMP} AND NOT "$ENV{TEMP}" STREQUAL "")
    set(temp_root "$ENV{TEMP}")
else()
    set(temp_root "${CMAKE_CURRENT_BINARY_DIR}")
endif()
set(SCRATCH_DIR "${temp_root}/vitasdk-sysroot-manifest-${fixture_id}")

set(triple arm-vita-eabi)
set(gcc_version 15.2.0)
set(stage1 "${SCRATCH_DIR}/stage1")
set(prefix "${SCRATCH_DIR}/prefix")

function(assert_present path)
    if(NOT EXISTS "${prefix}/${path}")
        message(FATAL_ERROR "expected ${path} to be imported")
    endif()
endfunction()

function(assert_absent path)
    if(EXISTS "${prefix}/${path}")
        message(FATAL_ERROR "${path} belongs to the host and must not be imported")
    endif()
endfunction()

function(write_stage1_tree)
    file(REMOVE_RECURSE "${stage1}")
    # Host binutils, installed again by every host under its own names.
    foreach(binary ld as ar nm objcopy strip)
        file(WRITE "${stage1}/${triple}/bin/${binary}" "host binary")
    endforeach()
    file(WRITE "${stage1}/${triple}/lib/libc.a" "target archive")
    file(WRITE "${stage1}/${triple}/lib/libstdc++.a" "target archive")
    file(WRITE "${stage1}/${triple}/include/stdio.h" "target header")
    # lib/gcc mixes the compiler proper with target objects.
    set(gcc_dir "${stage1}/lib/gcc/${triple}/${gcc_version}")
    foreach(target_file libgcc.a libgcov.a crtbegin.o crtend.o crti.o crtn.o crtfastmath.o)
        file(WRITE "${gcc_dir}/${target_file}" "target object")
    endforeach()
    foreach(host_file cc1 cc1plus lto1 collect2 lto-wrapper liblto_plugin.so)
        file(WRITE "${gcc_dir}/${host_file}" "host binary")
    endforeach()
    file(WRITE "${gcc_dir}/include/stdint.h" "compiler header")
    file(WRITE "${gcc_dir}/include-fixed/limits.h" "fixed header")
    file(WRITE "${gcc_dir}/sync-none.specs" "specs")
    file(WRITE "${stage1}/share/vita-headers/db.yml" "nid database")
    file(WRITE "${stage1}/share/gcc-${triple}/samples/CMakeLists.txt" "samples")
    file(WRITE "${stage1}/bin/${triple}-gcc" "host binary")
endfunction()

write_stage1_tree()
file(REMOVE_RECURSE "${prefix}")
vitasdk_import_sysroot("${stage1}" "${prefix}" "${triple}" "${gcc_version}")

assert_present("${triple}/lib/libc.a")
assert_present("${triple}/lib/libstdc++.a")
assert_present("${triple}/include/stdio.h")
assert_present("lib/gcc/${triple}/${gcc_version}/libgcc.a")
assert_present("lib/gcc/${triple}/${gcc_version}/libgcov.a")
foreach(crt_file crtbegin.o crtend.o crti.o crtn.o crtfastmath.o)
    assert_present("lib/gcc/${triple}/${gcc_version}/${crt_file}")
endforeach()
assert_present("share/vita-headers/db.yml")
assert_present("share/gcc-${triple}/samples/CMakeLists.txt")

# The host half of the SDK is built by the importing host, never imported.
assert_absent("${triple}/bin")
foreach(host_file cc1 cc1plus lto1 collect2 lto-wrapper liblto_plugin.so)
    assert_absent("lib/gcc/${triple}/${gcc_version}/${host_file}")
endforeach()
# include-fixed is regenerated by all-gcc against the imported headers, so the
# importing host owns it. Two owners would be one too many.
assert_absent("lib/gcc/${triple}/${gcc_version}/include")
assert_absent("lib/gcc/${triple}/${gcc_version}/include-fixed")
assert_absent("lib/gcc/${triple}/${gcc_version}/sync-none.specs")
assert_absent("bin/${triple}-gcc")

# A stage-1 SDK without the target objects cannot seed a stage-2 build, and
# saying so at import time beats a link failure at the end of gcc-final.
write_stage1_tree()
file(REMOVE "${stage1}/lib/gcc/${triple}/${gcc_version}/libgcc.a")
file(REMOVE_RECURSE "${prefix}")
execute_process(
    COMMAND ${CMAKE_COMMAND}
        -DSTAGE1_DIR=${stage1}
        -DPREFIX=${prefix}
        -DTARGET_TRIPLE=${triple}
        -DGCC_VERSION=${gcc_version}
        -P "${import_script}"
    RESULT_VARIABLE import_result
    OUTPUT_QUIET
    ERROR_VARIABLE import_error)
if(import_result EQUAL 0)
    message(FATAL_ERROR "importing a stage-1 SDK without libgcc.a must fail")
endif()
if(NOT import_error MATCHES "libgcc.a")
    message(FATAL_ERROR "the import failure must name the missing file, got: ${import_error}")
endif()

file(REMOVE_RECURSE "${SCRATCH_DIR}")
message(STATUS "Stage-1 sysroot manifest checks passed")
