function(GET_HOST_TRIPLET TRIPLET)
    set(host_arch ${CMAKE_HOST_SYSTEM_PROCESSOR})
    if (host_arch STREQUAL "x86")
        set(host_arch "i686")
    endif ()

    if (${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
        string(TOLOWER ${CMAKE_SYSTEM_NAME} host_os)
        set(host_release "gnu")
    elseif (${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
        set(host_os "w64")
        set(host_release "mingw32")
    elseif (${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
        set(host_os "apple")
        set(host_release "darwin")
    else ()
        message(FATAL "Unsupported system: ${CMAKE_SYSTEM_NAME}")
    endif ()

    set(${TRIPLET} "${host_arch}-${host_os}-${host_release}" PARENT_SCOPE)
endfunction()

function(GET_BUILD_TRIPLET TRIPLET)
    set(host_arch ${CMAKE_HOST_SYSTEM_PROCESSOR})
    if (host_arch STREQUAL "x86")
        set(host_arch "i686")
    endif ()

    if (${CMAKE_HOST_SYSTEM_NAME} STREQUAL "Linux")
        string(TOLOWER ${CMAKE_HOST_SYSTEM_NAME} build_os)
        set(build_release "gnu")
    elseif (${CMAKE_HOST_SYSTEM_NAME} STREQUAL "Windows")
        set(build_os "w64")
        set(build_release "mingw32")
    elseif (${CMAKE_HOST_SYSTEM_NAME} STREQUAL "Darwin")
        set(build_os "apple")
        set(build_release "darwin")
    else ()
        message(FATAL "Unsupported system: ${CMAKE_HOST_SYSTEM_NAME}")
    endif ()

    set(${TRIPLET} "${host_arch}-${build_os}-${build_release}" PARENT_SCOPE)
endfunction()
